spring:
  application:
    name: notification-service
server:
  port: 8085
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8081/eureka/
  instance:
    prefer-ip-address: true
    ip-address: localhost
    lease-renewal-interval-in-seconds: 30