spring:
  application:
    name: server
server:
  port: 8081

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8081/eureka/
  instance:
    ip-address: localhost
    prefer-ip-address: true