spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/123
    username: 123
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8082
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8081/eureka/
  instance:
    prefer-ip-address: true
    ip-address: localhost
    lease-renewal-interval-in-seconds: 30

jwt:
  access:
    secret: 123
    token-duration: 300000
  refresh:
    secret: 123@&*123
    token-duration:  604800000